name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run spellchecker
        run: npx yaspeller ${{ steps.get_file_changes.outputs.files }}

  build-site:
    runs-on: ubuntu-latest
    needs:
      - spellcheck
    steps:
      - uses: actions/checkout@v2

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Site
        run: npm run production

      - name: Create CNAME File
        run: echo "s-panteleev.ru" >> build_production/CNAME

      - name: Stage Files
        run: git add -f build_production

      - name: Commit files
        run: |
          git config --local user.email "sergey@php.net"
          git config --local user.name "Sergey Panteleev"
          git commit -m "Build for deploy"

      - name: Publish
        run: |
          git subtree split --prefix build_production -b gh-pages
          git push -f origin gh-pages:gh-pages